### ISSUE TITLE
Move into inwarcraft collective group

### ISSUE THREAD

**Issue by Frotty** [tdauth/wc3lib#11]
IIRC, water's main indent in inviting you was to get more projects into the group.
wc3lib would be the c++ equivalent then 🔗 
Just need to add CI

**Comment by tdauth** [comment]
How can I add it to the group? Can you just add a fork?

**Comment by Frotty** [comment]
Forking would just create a fork, I don't see the use in that.
See https://help.github.com/articles/about-repository-transfers/
You must transfer ownership, but of course you will stay admin of the project inside the group.
It's not necessary if you don't like that idea.

**Comment by tdauth** [comment]
I don't see any real benefits, so I will close this issue.

**Comment by Frotty** [comment]
and thats why no1 uses ur stuff -.-
